
name: 游뿐游뿐游뿐 Launch PR Merger 游뿐游뿐游뿐
on:
  workflow_dispatch:
    inputs:
        pr_number:
            type: number
            description: 'The PR number'
        commit_message:
            type: string
            description: 'The commit message'

permissions: write-all

jobs:
  send-pull-request:
    runs-on: ubuntu-latest

    steps:
         
      - name: Get funky
        uses: actions/checkout@v4
      - name: Merge
        uses: ./
        id: mergePR
        with:
          owner: 'elopezanaya'
          repo: 'cit-gh-actions-merge-pull-request'
          token: ${{ secrets.GITHUB_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          pull_number: ${{ github.event.inputs.pr_number }}
          commit_message : ${{ github.event.inputs.commit_message }}
      - name : PrintOutput
        run: | 
          echo "SHA ${{ steps.mergePR.outputs.sha }}"
          echo "status :  ${{ steps.mergePR.outputs.merged }}"
          


